// flow-typed signature: 4ff6bbad71ee57e17da8c679f895825e
// flow-typed version: <<STUB>>/serverless-webpack_v3.0.0-rc.2/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'serverless-webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'serverless-webpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'serverless-webpack/lib/cleanup' {
  declare module.exports: any;
}

declare module 'serverless-webpack/lib/compile' {
  declare module.exports: any;
}

declare module 'serverless-webpack/lib/index' {
  declare module.exports: any;
}

declare module 'serverless-webpack/lib/packageModules' {
  declare module.exports: any;
}

declare module 'serverless-webpack/lib/packExternalModules' {
  declare module.exports: any;
}

declare module 'serverless-webpack/lib/prepareLocalInvoke' {
  declare module.exports: any;
}

declare module 'serverless-webpack/lib/prepareOfflineInvoke' {
  declare module.exports: any;
}

declare module 'serverless-webpack/lib/run' {
  declare module.exports: any;
}

declare module 'serverless-webpack/lib/utils' {
  declare module.exports: any;
}

declare module 'serverless-webpack/lib/validate' {
  declare module.exports: any;
}

declare module 'serverless-webpack/lib/wpwatch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'serverless-webpack/index' {
  declare module.exports: $Exports<'serverless-webpack'>;
}
declare module 'serverless-webpack/index.js' {
  declare module.exports: $Exports<'serverless-webpack'>;
}
declare module 'serverless-webpack/lib/cleanup.js' {
  declare module.exports: $Exports<'serverless-webpack/lib/cleanup'>;
}
declare module 'serverless-webpack/lib/compile.js' {
  declare module.exports: $Exports<'serverless-webpack/lib/compile'>;
}
declare module 'serverless-webpack/lib/index.js' {
  declare module.exports: $Exports<'serverless-webpack/lib/index'>;
}
declare module 'serverless-webpack/lib/packageModules.js' {
  declare module.exports: $Exports<'serverless-webpack/lib/packageModules'>;
}
declare module 'serverless-webpack/lib/packExternalModules.js' {
  declare module.exports: $Exports<'serverless-webpack/lib/packExternalModules'>;
}
declare module 'serverless-webpack/lib/prepareLocalInvoke.js' {
  declare module.exports: $Exports<'serverless-webpack/lib/prepareLocalInvoke'>;
}
declare module 'serverless-webpack/lib/prepareOfflineInvoke.js' {
  declare module.exports: $Exports<'serverless-webpack/lib/prepareOfflineInvoke'>;
}
declare module 'serverless-webpack/lib/run.js' {
  declare module.exports: $Exports<'serverless-webpack/lib/run'>;
}
declare module 'serverless-webpack/lib/utils.js' {
  declare module.exports: $Exports<'serverless-webpack/lib/utils'>;
}
declare module 'serverless-webpack/lib/validate.js' {
  declare module.exports: $Exports<'serverless-webpack/lib/validate'>;
}
declare module 'serverless-webpack/lib/wpwatch.js' {
  declare module.exports: $Exports<'serverless-webpack/lib/wpwatch'>;
}
